import { MenuItem } from './types'

export const MENU_DATA: MenuItem[] = [
  {
    id: 'burger-1',
    name: 'Classic Veggie Burger',
    category: 'burgers',
    type: 'veg',
    price: 149,
    description: 'Crispy veggie patty with fresh lettuce, tomato, and special sauce',
    popular: true,
    available: true,
  },
  {
    id: 'burger-2',
    name: 'Spicy Chicken Burger',
    category: 'burgers',
    type: 'non-veg',
    price: 199,
    description: 'Juicy chicken patty with jalapeños, cheese, and chipotle mayo',
    popular: true,
    available: true,
  },
  {
    id: 'burger-3',
    name: 'Double Cheese Burger',
    category: 'burgers',
    type: 'non-veg',
    price: 249,
    description: 'Double beef patty with melted cheddar and American cheese',
    popular: false,
    available: true,
  },
  {
    id: 'burger-4',
    name: 'Paneer Tikka Burger',
    category: 'burgers',
    type: 'veg',
    price: 179,
    description: 'Spiced paneer tikka with mint chutney and crispy lettuce',
    popular: false,
    available: true,
  },
  {
    id: 'pizza-1',
    name: 'Margherita Pizza',
    category: 'pizza',
    type: 'veg',
    price: 299,
    description: 'Fresh mozzarella, basil, and tomato sauce on thin crust',
    popular: true,
    available: true,
  },
  {
    id: 'pizza-2',
    name: 'Pepperoni Pizza',
    category: 'pizza',
    type: 'non-veg',
    price: 349,
    description: 'Loaded with pepperoni slices and melted cheese',
    popular: false,
    available: true,
  },
  {
    id: 'pizza-3',
    name: 'Veggie Supreme',
    category: 'pizza',
    type: 'veg',
    price: 329,
    description: 'Bell peppers, onions, mushrooms, and olives',
    popular: false,
    available: true,
  },
  {
    id: 'pizza-4',
    name: 'BBQ Chicken Pizza',
    category: 'pizza',
    type: 'non-veg',
    price: 399,
    description: 'Tender chicken with tangy BBQ sauce and cheddar',
    popular: false,
    available: true,
  },
  {
    id: 'fries-1',
    name: 'Classic French Fries',
    category: 'fries',
    type: 'veg',
    price: 99,
    description: 'Crispy golden fries with sea salt and herbs',
    popular: true,
    available: true,
  },
  {
    id: 'fries-2',
    name: 'Loaded Cheese Fries',
    category: 'fries',
    type: 'veg',
    price: 149,
    description: 'Topped with melted cheddar, bacon bits, and green onions',
    popular: false,
    available: true,
  },
  {
    id: 'fries-3',
    name: 'Peri Peri Fries',
    category: 'fries',
    type: 'veg',
    price: 129,
    description: 'Spicy peri peri seasoning with lemon and chili',
    popular: false,
    available: true,
  },
  {
    id: 'drink-1',
    name: 'Cold Coffee',
    category: 'drinks',
    type: 'veg',
    price: 129,
    description: 'Chilled coffee blend with ice cream and cream',
    popular: true,
    available: true,
  },
  {
    id: 'drink-2',
    name: 'Fresh Lime Soda',
    category: 'drinks',
    type: 'veg',
    price: 79,
    description: 'Refreshing lime juice with soda and mint',
    popular: false,
    available: true,
  },
  {
    id: 'drink-3',
    name: 'Mango Smoothie',
    category: 'drinks',
    type: 'veg',
    price: 149,
    description: 'Creamy smoothie made with fresh mango and yogurt',
    popular: false,
    available: true,
  },
  {
    id: 'dessert-1',
    name: 'Chocolate Brownie',
    category: 'desserts',
    type: 'veg',
    price: 159,
    description: 'Rich and fudgy chocolate brownie with vanilla ice cream',
    popular: true,
    available: true,
  },
  {
    id: 'dessert-2',
    name: 'Cheesecake',
    category: 'desserts',
    type: 'veg',
    price: 189,
    description: 'Creamy New York style cheesecake with berry topping',
    popular: false,
    available: true,
  },
]

export const CATEGORIES = [
  { icon: '🍽️', label: 'All', value: 'all' },
  { icon: '🍔', label: 'Burgers', value: 'burgers' },
  { icon: '🍕', label: 'Pizza', value: 'pizza' },
  { icon: '🍟', label: 'Fries', value: 'fries' },
  { icon: '🥤', label: 'Drinks', value: 'drinks' },
  { icon: '🍰', label: 'Desserts', value: 'desserts' },
]
